### ISSUE TITLE
Wrong PCB hole diameter

### ISSUE THREAD

**Issue by krotos139** [knaufinator/6DOF-Rotary-Stewart-Motion-Simulator#10]
Wrong PCB holes for screw terminals.

**Comment by knaufinator** [comment]
to small?  I had these blue ones laying around in my shop, and they fit. suggestions?
![IMG_20200911_210004](https://user-images.githubusercontent.com/11393583/99681756-85774780-2a4c-11eb-9b6f-350b42a9c5be.jpg)

**Comment by krotos139** [comment]
I bought this screw terminals:
![изображение](https://user-images.githubusercontent.com/2933707/99720227-e3e10c00-2ac6-11eb-8438-88f98fe4995f.png)
This terminals looks like your. This screw terminal has pin thikness 1mm:
![изображение](https://user-images.githubusercontent.com/2933707/99720460-37ebf080-2ac7-11eb-8cb6-31ff5655ad78.png)
But PCB has hole size is 0.915 mm. And I cannot insert it easy.

Have you had any problems installing these terminals?

**Comment by knaufinator** [comment]
Mine were used/desoldered from an old project, they fit.. but it was snug,.. I assumed because of the solder-remains 

I checked the part in the schematic and it looks like @0.915mm diam. so spot on measure..

I have found based on your picture, this schematic part that looks like it would fit better, 
![image](https://user-images.githubusercontent.com/11393583/99724599-db1a1700-2a81-11eb-97ca-f82961bae63b.png)

I will update the PCB's with this screw terminal, I agree that this would be better. thanks... I will try to do it today

**Comment by knaufinator** [comment]
Updated both PCB Gerbers, with 1.1mm pitch screw terminals, Thanks @krotos139
